- docs/decisions/00-template.md
- docs/decisions/01-system-design-guidance.md
I hope you're familiar with ADRs. If not, the basic idea is to write down both the more significant choices made in a project, as well as the reasoning that went into them. And they often go in source control because as programmers we are obligated to use that particular hammer for every single nail.
So with this, I guess I want to know if the logic and the choices make sense and seem reasonable, or if you can think of anything I missed.
> ADR for architecture guidance

- .github/workflows/pull-request.yml
- .github/workflows/push-to-main.yml
- Letterbook.Api.Tests/Letterbook.Api.Tests.csproj
- Letterbook.Api.Tests/SnakeCaseRouteTransformerTest.cs
- Letterbook.Api.Tests/Usings.cs
Adding an xunit project to test the project and place the snake_case converter under test.
Add two CI jobs to validate pull requests against `main` and pushes made to `main`
> Put Snake_Case Converter under test and add initial CI workflows

- readme.md
Feel free to add yourself as a maintainer, if you like.
> less barren readme

- Letterbook.Adapter.Db/Entities/AddressedRelationship.cs
- Letterbook.Adapter.Db/Entities/JoinObjectActor.cs
- Letterbook.Api/Controllers/ActivityPub/ActorController.cs
- Letterbook.Api/GlobalUsings.cs
- Letterbook.Api/Letterbook.Api.csproj
- Letterbook.Core.Tests/ActivityTest.cs
- Letterbook.Core/ActivityService.cs
- Letterbook.Core/GlobalUsings.cs
- Letterbook.Core/IActivityService.cs
- Letterbook.Core/Letterbook.Core.csproj
- Letterbook.Core/Models/ActivityObjectType.cs
- Letterbook.Core/Models/Actor.cs
- Letterbook.Core/Models/ApObject.cs
- Letterbook.Core/Models/Audience.cs
The Letterbook AP models will need a little bit of work before they're ready for prime time, but that's okay, the other lib needed more. They'll be *much* easier to work with, and I don't want to write a bunch of type mappers twice, so I'm doing this now.
- #38
> Migrate to Letterbook ActivityPub DTOs

- .github/.github/ISSUE_TEMPLATE/bug_report.md
- .github/.github/ISSUE_TEMPLATE/feature_request.md
- .github/.github/ISSUE_TEMPLATE/task.md
- .github/.github/pull_request_template.md
Added templates
- Issues
- PRs
- closes #54
> Add github templates

- Letterbook.Api/Program.cs
Even if profile service not implemente, at least I have a sense of something more working then before.
> Make small changes to make code runnable

- CODE_OF_CONDUCT.md
Clarify what self determination means, based on some discussion with other contributors
> Clarify self determination

- readme.md
Adds some background to the readme
> Background

- Letterbook.Adapter.TimescaleFeeds/FeedsAdapter.cs
- Letterbook.Adapter.TimescaleFeeds/FeedsDbOptions.cs
- Letterbook.Api.Tests/.globalconfig
- Letterbook.Api.Tests/Fakes/FakeActivity.cs
- Letterbook.Api/WebFingerJsonResourceDescriptor.cs
- Letterbook.Core.Tests/AccountServiceTest.cs
- Letterbook.Core.Tests/Fakes/FakeNote.cs
- Letterbook.Core.Tests/Fakes/FakeProfile.cs
- Letterbook.Core.Tests/TimelineServiceTest.cs
- Letterbook.Core/Models/Audience.cs
- Letterbook.Core/Models/Image.cs
- Letterbook.Core/Models/Mention.cs
- Letterbook.Core/Models/Note.cs
- Letterbook.Core/Models/ObjectCollection.cs
- Letterbook.Core/Models/ObjectList.cs
- Letterbook.Core/Models/Profile.cs
Just doing some chores
- Most the remaining warnings are real problems
- Consider them TODO items
> Cleanup warnings

- Letterbook.Adapter.Db/AccountProfileAdapter.cs
- Letterbook.Core.Tests/AccountEventServiceTest.cs
- Letterbook.Core.Tests/Extensions/AsyncEnumberable.cs
- Letterbook.Core.Tests/Fakes/FakeProfile.cs
- Letterbook.Core.Tests/Letterbook.Core.Tests.csproj
- Letterbook.Core.Tests/ProfileServiceTests.cs
- Letterbook.Core/AccountEventService.cs
- Letterbook.Core/Adapters/IAccountEventService.cs
- Letterbook.Core/Adapters/IAccountProfileAdapter.cs
- Letterbook.Core/Adapters/IProfileEventService.cs
- Letterbook.Core/CoreOptions.cs
- Letterbook.Core/IProfileService.cs
- Letterbook.Core/ITimelineService.cs
- Letterbook.Core/Models/Account.cs
- Letterbook.Core/Models/CustomField.cs
- Letterbook.Core/Models/Profile.cs
- Letterbook.Core/Models/UpdateResponse.cs
- Letterbook.Core/ProfileService.cs
- Letterbook.Core/TimelineService.cs
- Letterbook.sln.DotSettings
> Implements more of the profile service

- Letterbook.Api/Letterbook.Api.csproj
- Letterbook.Api/Program.cs
- Letterbook.Api/appsettings.json
Adding structured logging to hopefully help make debugging/monitoring a bit more approachable. This is a first pass - will probably need more thought in order to support additional sinks depending on where this is hosted.
- Introduces a dependency on [`Serilog.AspNetCore`](https://github.com/serilog/serilog-aspnetcore)
- Logging is configured in `appsettings.json` under `Serilog`. [More about how to do that here](https://github.com/serilog/serilog-settings-configuration).
- Mostly mirrors default .NET logging behavior but with a bit more structure.
I'm most familiar with `Serilog` for structured logging in .NET so that's what I've used here, there may be other options worth pursuing I'm less familiar with.
> Introduce Serilog logger

- Letterbook.Api/appsettings.Development.json
- Letterbook.Api/appsettings.Sandcastle.json
Make the logging config consistent between development and sandcastle environments
> Consistent logging config

- global.json
Default to SDK version 8
as that's what's in use throughout
This is used by command-line tools
- Are there any technical details you need to explain?
- New patterns, or deviations from existing patterns?
- link issues, this helps when preparing release notes
- use closing keywords, if appropriate
> Default to SDK version 8

- docs/decisions/09-formatting.md
following https://github.com/Letterbook/Letterbook/pull/179, and ADR document explaining what and why. Some content is recycled from the PR text and comments.
- Are there any technical details you need to explain?
- New patterns, or deviations from existing patterns?
- link issues, this helps when preparing release notes
- use closing keywords, if appropriate
Please feel free to rewrite this if it's not what you need.
> Formatting and editorconfig ADR document

- Letterbook.Api.Tests/MapperTests.cs
- Letterbook.Api.Tests/PostsControllerTests.cs
- Letterbook.Api/Dto/FullProfileDto.cs
- Letterbook.Api/Dto/PublicKeyDto.cs
- Letterbook.Api/Mappers/BaseMappings.cs
- Letterbook.Api/Mappers/Converters/DateTimeOffsetMapper.cs
- Letterbook.Api/Mappers/Converters/IdUuid7Converter.cs
- Letterbook.Api/Mappers/MappingConfigProvider.cs
- Letterbook.Api/Mappers/PostMappings.cs
- Letterbook.Api/Mappers/ProfileMappings.cs
- Letterbook.Api/Program.cs
Adds a DTO and mapper to handle Profiles in API calls
- Add a new mapper config for profiles
- Refactor some existing mappers to smaller and more targeted profiles
- Trying to keep things to a reviewable size
- re #194
> Profile DTO

- .github/workflows/renovate.yml
Looking for a better update cadence
> Adjust renovate schedule

- .gitignore
- Http/Api.http
- Http/Endpoints.http
- Http/http-client.env.json
- Letterbook.Adapter.ActivityPub/Client.cs
- Letterbook.Api.Authentication.HttpSignature/Handler/HttpSignatureAuthenticationHandler.cs
- Letterbook.AspNet/ProfileIdentityMiddleware.cs
- Letterbook.Core/Extensions/DependencyInjection.cs
- Letterbook.Core/Instrumentation.cs
- Letterbook.Dashboards/Grafana/provisioning/dashboards/definitions/operations/dash-api-overview.json
- Letterbook.Dashboards/Grafana/provisioning/dashboards/definitions/operations/trace-detail.json
- Letterbook/Program.cs
- Letterbook/Properties/launchSettings.json
- Letterbook/appsettings.Sandcastle.json
Improves some of the telemetry we emit and collect, and provides some more useful debugging dashboards. Also cleans up the http request templates and other debugging resources that had gotten badly stale.
> chore: Improve telemetry

- Letterbook.Docs/Letterbook.Docs.csproj
- Letterbook.Docs/Pages/Author/Page.cshtml.cs
- Letterbook.Docs/Pages/Blog/Page.cshtml.cs
- Letterbook.Docs/Pages/Docs/Page.cshtml.cs
- Letterbook.Docs/Pages/Guides/Page.cshtml.cs
- Letterbook.Docs/Pages/Shared/_Layout.cshtml
- Letterbook.Docs/libman.json
- Letterbook.Docs/wwwroot/js/mermaid-config.js
Render mermaid diagrams and enable hot reload on content pages
> docs: mermaid

- Letterbook.Docs/_blog/2024-12-26/office hours.md
Blog post for office hours
Sorry for the short notice. I wasn't sure I'd have the energy for it until very recently.
> docs(blog): dec office hours

- Letterbook.Docs/_blog/2024-11-18/moderation-tooling-research.md
Gives a more informative first look, and link previews
> docs: adjust the title elements

- Letterbook.Docs/Pages/NotFound.cshtml
Use absolute paths to css and img assets
> docs: fix broken css in not found page

- Letterbook.Core/Models/Profile.cs
- Letterbook.Core/Workers/SeedAdminWorker.cs
- Letterbook.IntegrationTests/Fixtures/HostFixture.cs
Create special system profiles
- Define static Profiles on the Profile class
- Seed them to the db on startup
> feat: system profiles

- Source/Letterbook.Adapter.ActivityPub/Mappers/AstMapper.cs
- Source/Letterbook.Api/ActivityPub/ActorController.cs
- Source/Letterbook.Api/Controllers/ProfilesController.cs
- Source/Letterbook.Core/IModerationService.cs
- Source/Letterbook.Core/Models/ModerationRemark.cs
- Source/Letterbook.Core/Models/ModerationReport.cs
- Source/Letterbook.Core/Models/Post.cs
- Source/Letterbook.Core/Models/Profile.cs
- Source/Letterbook.Core/ModerationService.cs
- Tests/Letterbook.Adapter.ActivityPub.Test/MapperTests.cs
- Tests/Letterbook.Api.Tests/ActorControllerTests.cs
- Tests/Letterbook.Core.Tests/ModerationServiceTests.cs
- Tests/Letterbook.IntegrationTests/InboxTests.cs
- docs/OpenApi/letterbook-v1.json
This just wires up the inbox controller to handle Flag activities.
- Add the controller
- Add mapper configs for Flag -> ModerationReport
- Add tests for that
- closes #404
> feat: report federation

- Letterbook.Docs/Properties/launchSettings.json
- Source/Letterbook.Api/Properties/launchSettings.json
- Source/Letterbook.Web/Properties/launchSettings.json
- Source/Letterbook.Workers/Properties/launchSettings.json
Cleanup and simplify launch settings across all projects
> chore: simplify launch settings

- Source/Letterbook.Core/Workers/SeedAdminWorker.cs
Fixes the db seed so that the admin account seed can actually happen.
> fix: admin account

- Letterbook.Docs/_blog/2025-04-22/mission.md
- Letterbook.Docs/_pages/index.md
Adds a blog post to clearly detail the mission, vision, and values of the project.
Inspired by this article https://werd.io/2025/if-i-ran-mastodon
> docs: mission and values blog post
