Letterbook/Letterbook

Letterbook.Adapter.Db/Entities/ConfigureAudience.cs, Letterbook.Adapter.Db/Entities/ConfigureImage.cs, Letterbook.Adapter.Db/Entities/ConfigureNote.cs, Letterbook.Adapter.Db/Migrations/20230727051434_Fix_Navigations.Designer.cs, Letterbook.Adapter.Db/Migrations/20230727051434_Fix_Navigations.cs, Letterbook.Core/Models/Image.cs
I think the configurations are pretty readable, but the snapshot certainly is not. Things to look for include:
* Profile no longer has FKeys to Notes and Images, but instead has join tables like it should have had in the first place.
* Audience, Mention, etc are now those join tables instead of whatever the heck they were doing before.
* Most of these things have useful table and column names so we might have some idea what the heck we're looking at when we need to go SQL spelunking.
TBH, I'm still not 100% sure Mentions are correct, but it's a heck of a lot better.
=> fix the db schema some more because relationships are hard

CONTRIBUTING.md, Letterbook.Adapter.Db/readme.md
discuss installing and setting up Entity Framework in the contributing docs and setting up the EF tooling from a clean dotnet install.
=> Update contributing docs with EF installation/migrations

Letterbook.Api/Letterbook.Api.csproj, Letterbook.Api/Program.cs, Letterbook.Dashboards/Grafana/provisioning/datasources/prometheus.yml, Letterbook.Dashboards/Prometheus/prometheus.yml, Letterbook.Dashboards/README.md, docker-compose.yml
Adding ASP.NET core telemetry and configuring basic prometheus + grafana endpoints. This should get us to the point where we can start recording and observing metrics, intended as a starting point for this work. By default we'll get a record of a the duration of web requests in milli's. The default behavior is discussed in more depth [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/README.md).
The `provisioning/dashboards` path is kept around for future use in automatic dashboard provisioning. Implementing that now isn't super useful though since telemetry is limited.
- This introduces two new containers started w/ the project: Prometheus and Grafana. This is sensitive to the port you're running the project on and can …
=> Add OTel, Prometheus and Grafana

Letterbook.Api/Letterbook.Api.csproj, Letterbook.Api/appsettings.Development.json, Letterbook.Api/appsettings.json, Letterbook.Dashboards/Grafana/provisioning/datasources/loki.yml, docker-compose.yml
This introduces [Grafana Loki](https://grafana.com/docs/loki/latest/) and connects the logs of `Letterbook.API` to `Grafana` so they can be read.
This will allow us to view app logs in Grafana and configure alerts for them.
Testing this:
1. run `docker-compose`
1. run `Letterbook.API`
1. open Grafana at `localhost:3000`
1. Open your [data sources](http://localhost:3000/connections/datasources)
1. Select `Explore` on Loki.
=> Add Loki Logging

Letterbook.Dashboards/Grafana/provisioning/datasources/postgres.yml, Letterbook.Dashboards/Grafana/provisioning/datasources/timescale.yml
I don't know if we actually want this but it introduces access for both Postgres DB's in Grafana so queries can be run against tables in both of them. This allows inspecting of those DB's from inside of Grafana and potentially future use for telemetry and usage metrics for the server (ex. dashboards showing most active users).
Part of #116
=> Add ability to query postgres db's in grafana.

Letterbook.Core/Models/Post.cs, Letterbook.sln, docs/decisions/07-posts-data-model.md
Proposes a change to the content data model, which should make both inbound activity processing and general maintenance easier. It's an ADR, so the ADR doc itself is really the best description.
https://github.com/Letterbook/Letterbook/compare/adr/post-data-model?expand=1&short_path=50f4b27#diff-50f4b271e491af84f4eaadb6740d8ca218ff6a810c2441bab15fb76eab205958
- Introduce the concept of a post
- Concepts like Notes and Images then become content within a post
- #139 
- #126
=> ADR-07: post data model

CONTRIBUTING.md, Letterbook.Adapter.Db/readme.md
- some additions to the documentation which I believe will help the "I've cloned it and want to run it locally" first-time dev experience.
=> provide additional context for first-dev-run documentation

Letterbook.Adapter.Db/Letterbook.Adapter.Db.csproj, Letterbook.Adapter.Db/Migrations/20240107192358_UpdateFrameworkV8.Designer.cs, Letterbook.Adapter.Db/Migrations/20240107192358_UpdateFrameworkV8.cs, Letterbook.Adapter.Db/RelationalContext.cs
Npgsql added an explicit opt-in to dynamic json serialization for json/jsonb columns in dotnet 8. So, we have to opt-in. And get on a consistent version of Npgsql throughout the solution, while we're at it.
- Just what it says on the tin
- Fixes the startup crash reported by @mattly (TY!)
For the curious, it's likely I didn't notice that crash before now because the only real time we try to create profiles with custom fields at the moment is when seeding the db with a default admin account. Which I haven't needed to do recently.
=> Fix insert/update on Profiles

Letterbook.Adapter.ActivityPub.Test/ExtensionTests.cs, Letterbook.Adapter.ActivityPub.Test/MapperTests.cs, Letterbook.Adapter.ActivityPub/Extensions.cs, Letterbook.Adapter.ActivityPub/Letterbook.Adapter.ActivityPub.csproj, Letterbook.Adapter.ActivityPub/Mappers/AstMapper.cs, Letterbook.Adapter.Db/EntityConfigs/ConfigureContent.cs, Letterbook.Adapter.Db/EntityConfigs/ConfigurePost.cs, Letterbook.Adapter.Db/EntityConfigs/ConfigureThreadContext.cs, Letterbook.Adapter.Db/Migrations/20240112053915_FixPostProperties.Designer.cs, Letterbook.Adapter.Db/Migrations/20240112053915_FixPostProperties.cs, Letterbook.Api/Letterbook.Api.csproj, Letterbook.Core/Letterbook.Core.csproj, Letterbook.Core/Models/Audience.cs, Letterbook.Core/Models/IContent.cs, Letterbook.Core/Models/Mention.cs, Letterbook.Core/Models/Note.cs, Letterbook.Core/Models/Post.cs, Letterbook.Core/Models/ThreadContext.cs
Adds basic mapping configs for ASNote, including many APSharp generics.
- We're making pretty heavy use of custom type converters and value resolvers. AS types are really complex, so I'm not sure I see a way around that. Hopefully it's not too hard to follow.
- closes #154
=> AST to Post mappers

Letterbook.Adapter.ActivityPub.Test/Letterbook.Adapter.ActivityPub.Test.csproj
Remove this dangling folder include for `Fixtures` from `Letterbook.Adapter.ActivityPub.Test.csproj` The folder does not exist.
If it did, it would be included by default, There is in most cases no need to manually include a folder
This is likely cruft, unless there is a specific reason for it (such as generated code?)
- Are there any technical details you need to explain?
- New patterns, or deviations from existing patterns?
- link issues, this helps when preparing release notes
- use closing keywords, if appropriate
=> Remove this dangling folder include

Letterbook.Api.Tests/Letterbook.Api.Tests.csproj, Letterbook.Api/Letterbook.Api.csproj, Letterbook.Core.Tests/Letterbook.Core.Tests.csproj, Letterbook.Core/Letterbook.Core.csproj
Remove cruft from csproj files
* `Letterbook.Api.Tests/Fakes` Folder does not exist, and if it did, it would be included by default. Including it explicitly has no effect.
* `Letterbook.Api/Mappers`  Folder does not exist, same.
* `Letterbook.Core/Mappers`  Folder does not exist, same.
* `Letterbook.Api/Controllers/WebFingerController.cs` File does not exist, removing it in csproj has no effect.
* `Letterbook.Core.Tests/Letterbook.Core.Tests.csproj` removed extra spaces
- Are there any technical details you need to explain?
- New patterns, or deviations from existing patterns?
No.
- link issues, this helps when preparing release notes
- use closing keywords, if appropriate
=> Remove cruft from csproj files

Letterbook.Adapter.ActivityPub/Letterbook.Adapter.ActivityPub.csproj, Letterbook.Api.IntegrationTests/Letterbook.Api.IntegrationTests.csproj, Letterbook.Api.Tests/Letterbook.Api.Tests.csproj, Letterbook.Core/Letterbook.Core.csproj
Over time, some packages snuck into our imports that we don't actually use. This removes them.
- Newtonsoft
- JsonDiffPatch
- NJsonSchema
(huh, it's all json)
=> Cleanup unused imports

.github/workflows/pull-request.yml
Update node github Actions to V4
As these currently run on Node.js 16, which is deprecated in favour actions on of Node.js 20
Note the message here: https://github.com/Letterbook/Letterbook/actions/runs/8119876091
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: 
actions/checkout@v3, actions/setup-dotnet@v3. 
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Intent is to remove this warning.
This node version update is documented on the release pages of these actions for v4:
`actions/checkout`: https://github.com/actions/checkout/releases
`actions/setup-dotnet`: https://github.com/actions/setup-dotnet/releases
There have been multiple rounds of this, the latest GHA node …
=> Update node github Actions to V4

Letterbook.Api/Controllers/ActivityPub/ActorController.cs, Letterbook.Api/Controllers/ActivityPub/ObjectController.cs, Letterbook.Api/Controllers/Debugging/DebugController.cs, Letterbook.Api/Controllers/Mastodon/AccountsController.cs, Letterbook.Api/Controllers/UserAccountController.cs, Letterbook.Api/Dto/Id25.cs, Letterbook.Api/Swagger/DependencyInjection.cs, Letterbook.Api/Swagger/Docs.cs
This allows us to generate multiple OpenAPI docs, and swap between them in the Swagger UI. This should give a more focused experience when interacting with the Swagger UI.
- Generate multiple swagger.json files:
- letterbook-v1
- mastodon-v1
- activity-pub-v1
- Configure the swagger UI to load and swap between them using the definition selector
- Move the (now extensive) swagger config into DI extension methods
=> Organize Swagger docs

Letterbook.Adapter.ActivityPub.Test/ClientTests.cs, Letterbook.Adapter.ActivityPub.Test/TestData.cs
Small fix for a race condition in the tests
- Now that multiple test projects depend on the Actor.json test data file, they might try to read it at the same time
- This change permits them to do so
- Previously, one of them would sometimes throw
=> Fix race while reading test data files

Letterbook.Api.Tests/ActorControllerTests.cs, Letterbook.Api.Tests/ProfileControllerTests.cs, Letterbook.Api.Tests/WebfingerTests.cs, Letterbook.Api/Controllers/ActivityPub/ActorController.cs, Letterbook.Api/Controllers/Debugging/DebugController.cs, Letterbook.Api/Controllers/ProfileController.cs, Letterbook.Api/WebfingerProvider.cs, Letterbook.Core.Tests/WithMocks.cs, Letterbook.Core/IProfileService.cs, Letterbook.Core/ProfileService.cs
This is just some refactoring to support upcoming work on the Profile API
- Alters the `ProfileService` to implement the usual dual `IProfileService` and `IAuthzProfileService` interfaces
- Updates tests and dependents accordingly
- re #167 
- re #194
=> Adapt profile service to fit authz model

Letterbook.Adapter.Db/DependencyInjection.cs
Moves the datasource creation to the parent scope, so it's reused properly
- ty @mattly for reporting
=> Reuse npgsql datasource properly

Letterbook.Web/Pages/Profile.cshtml, Letterbook.Web/Pages/Profile.cshtml.cs
This displays basic profile information on the profile page. I edited my profile in postgres directly to provide description and custom fields: 
- I really do not want to expose the main `Prof` model to the template for reasons discussed in Discord. For posterity, the concern is about keeping an inventory of work done (database access, etc) outside the templates. The main model has a number of methods available that can do all sorts of things, and those should not be available to the template. I'm still new to dotnet / csharp, but the way I found to do this was by making the `Prof` field `private protected` and nullable; anything else I tried either still exposed that field to the template or gave me compiler warnings/errors.
Further things that could be useful here:
- how do I get a list …
=> basic profile display

Letterbook.Adapter.ActivityPub.IntegrationTests/ActivityPubClientCompositeTests.cs, Letterbook.Adapter.ActivityPub.IntegrationTests/HostFixture.cs, Letterbook.Adapter.ActivityPub.Test/MapperTests.cs, Letterbook.Api.IntegrationTests/Fixtures/HostFixture.cs, Letterbook.Api.IntegrationTests/PostsTests.cs, Letterbook.Api/Program.cs, Letterbook.Core.Tests/TestData.cs
Sets up (some, more to come) integration tests to run with a dedicated database per class, which eliminates the biggest source of conflicts and makes them more parallelizable.
- Override the config used in tests
- Set a unique database name, based on the test class
- Skip the bootstrap logger during tests
=> Reduce integration test conflicts

Letterbook.Api/DependencyInjectionExtensions.cs, Letterbook.Api/Program.cs, Letterbook.Web/Areas/Identity/Pages/Account/Login.cshtml, Letterbook.Web/Areas/Identity/Pages/Account/Login.cshtml.cs, Letterbook.Web/Areas/Identity/Pages/Account/Logout.cshtml, Letterbook.Web/Areas/Identity/Pages/Account/Logout.cshtml.cs, Letterbook.Web/Areas/Identity/Pages/Account/Register.cshtml, Letterbook.Web/Areas/Identity/Pages/Account/Register.cshtml.cs, Letterbook.Web/Areas/Identity/Pages/Account/_ValidationScriptsPartial.cshtml, Letterbook.Web/Areas/Identity/Pages/Account/_ViewImports.cshtml, Letterbook.Web/Areas/Identity/Pages/Account/_ViewStart.cshtml, Letterbook.Web/GlobalUsings.cs, Letterbook.Web/Pages/Profile.cshtml.cs, Letterbook.Web/Pages/Shared/_Layout.cshtml, Letterbook.Web/Pages/Shared/_LoginPartial.cshtml, Letterbook.Web/Program.cs
Adds default(ish) account registration, login, and logout pages from Aspnet Identity, and (actually) default account maintenance pages, to allow managing account data like change email and password resets.
The default UI is not one that we'll want to keep long term, but I think it will be helpful as a starting point, and just during development.
- Use identity default UI via `AddDefaultUI()` builder method
- Override a handful of basic pages so they'll actually work
- Scaffolding the pages is basically impossible in app where the dbcontext is in another project than the mvc app.
- Many of the unscaffolded defaults don't actually work
=> enhancement(web): default register, login, logout

Letterbook.Web/appsettings.Development.json
Adds the `Letterbook.FeedsDatabase` required config option to the web app's development settings. The server will error if this is not present
=> add FeedsDatabase to Web app settings

Letterbook.Adapter.ActivityPub/Signatures/ClientHandler.cs, Letterbook.Core/Models/Profile.cs, Letterbook.Core/ProfileService.cs
Apparently they cannot handle slashes in the fragment. I feel like I might have discovered that once before?
> [!TIP]
> You might want to drop and recreate your local database, or at least create new profiles to test federation after this fix
To get activities from existing profiles to federate, you'll have to change the fediId on the signing keys.
- Mastodon just doesn't validate signatures when the key has a slash `/` in the fragment
- It is completely valid and acceptable to have slashes in the fragment portion of a URL
- c'est la mastodon, I guess
=> fix signatures for mastodon

.github/workflows/pull-request.yml, CONTRIBUTING.md, Directory.Packages.props, Letterbook.Web.Tests.E2E/LandingPageValidationTest.cs, Letterbook.Web.Tests.E2E/Letterbook.Web.Tests.E2E.csproj, Letterbook.Web.Tests.E2E/OneTimeSetup.cs, Letterbook.Web.Tests.E2E/README.md, Letterbook.Web.Tests.E2E/SelfStartedWebServerExampleTest.cs, Letterbook.Web.Tests.E2E/Support/Playwright.cs, Letterbook.Web.Tests.E2E/Support/Settings.cs, Letterbook.Web.Tests.E2E/Support/WebServerFixture.cs, Letterbook.Web.Tests.E2E/Using.cs, Letterbook.Web.Tests/Letterbook.Web.Tests.csproj, Letterbook.sln
The changes here have the build passing with this end-to-end test from #207 
https://github.com/ben-biddington/Letterbook/blob/f/add-playwright-testing-project-to-main-%23205/Letterbook.Web.Tests.E2E/LandingPageValidationTest.cs
So I think you're free to continue in this style if you wanted to while experimenting with the on-demand server idea.
There are also some examples showing how you could run the tests against a server started at runtime:
https://github.com/ben-biddington/Letterbook/blob/f/add-playwright-testing-project-to-main-%23205/Letterbook.Web.Tests.E2E/SelfStartedWebServerExampleTest.cs
This could be useful if you wanted to be able to change the application under test. For example you may wish to substitute some of the services for fakes.
These tests use …
=> f/add playwright testing project to main #205

Directory.Packages.props, Letterbook.Adapter.Db/Migrations/20240811185620_ContentTypeRequired.Designer.cs, Letterbook.Adapter.Db/Migrations/20240811185620_ContentTypeRequired.cs, Letterbook.Core.Tests/MapperTests.cs, Letterbook.Core.Tests/Mocks/MockHtmlSanitizer.cs, Letterbook.Core.Tests/PostServiceTests.cs, Letterbook.Core/Extensions/DependencyInjection.cs, Letterbook.Core/HtmlSanitizer.cs, Letterbook.Core/IContentSanitizer.cs, Letterbook.Core/Letterbook.Core.csproj, Letterbook.Core/Models/Content.cs, Letterbook.Core/Models/Dto/ContentDto.cs, Letterbook.Core/Models/IContent.cs, Letterbook.Core/Models/Mappers/PostMappings.cs, Letterbook.Core/Models/Note.cs, Letterbook.Core/PostService.cs, Letterbook.Core/TextSanitizer.cs, docs/OpenApi/letterbook-v1.json
Adds content type-aware sanitization, and sanitizes posts along all create/update paths
Also, note the migration. When adding migrations, sometimes you need to help them out a little. Dotnet-ef will give a message like:
```shell
$ dotnet ef migrations add ContentTypeRequired
Build started...
Build succeeded.
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.
Done. To undo this action, use 'ef migrations remove'
```
In this case, it was due to adding a NOT NULL constraint on the `ContentType` column. We can easily provide a default, using the `migrationBuilder`. This is something I want to get better about doing. In the past, I've just blown away migrations and started over, but the time is coming when that's not an option any more. …
=> chore: sanitize posts

Letterbook.Workers/Consumers/DeliveryWorker.cs, Letterbook.Workers/Consumers/TimelineConsumer.cs, Letterbook.Workers/Contracts/AccountEvent.cs, Letterbook.Workers/Contracts/ActivityMessage.cs, Letterbook.Workers/Contracts/Claim.cs, Letterbook.Workers/Contracts/PostEvent.cs, Letterbook.Workers/Extensions.cs, Letterbook.Workers/Publishers/AccountEventPublisher.cs, Letterbook.Workers/Publishers/PostEventPublisher.cs
Use a serializable claim DTO in worker contracts
- It turns out `System.Security.Claims.Claim` doesn't serialize to json; who knew :woman_shrugging: :sweat_smile: 
- prep for #191
=> fix: serializable claims

Letterbook.Adapter.ActivityPub.Test/MapperTests.cs, Letterbook.Adapter.ActivityPub/Document.cs, Letterbook.Adapter.ActivityPub/Extensions.cs, Letterbook.Adapter.ActivityPub/Mappers/AstMapper.cs, Letterbook.Core/Adapters/IActivityPubDocument.cs, Letterbook.Core/Models/Post.cs
Automapper configs for post models to AS types
- Mostly routine mappers
- Restored some previously skipped tests, now that we can map them again
- prep work for #191
=> chore: add mappings for posts -> AS types

Letterbook.Adapter.Db/DataAdapter.cs, Letterbook.Adapter.Db/EntityConfigs/ConfigureProfile.cs, Letterbook.Adapter.Db/Migrations/20240916044339_AddProfileAuthority.Designer.cs, Letterbook.Adapter.Db/Migrations/20240916044339_AddProfileAuthority.cs, Letterbook.Core.Tests/Fakes/FakePost.cs, Letterbook.Core.Tests/Fakes/FakeProfile.cs, Letterbook.Core/Extensions/CoreOptionsExtensions.cs, Letterbook.Core/Models/Profile.cs
The Authority field is the hierarchically ordered domain name from the FediId. That is, like `tld.domain.subdomain`. This is useful for doing fast queries to match a domain and all of its subdomains and ports, or exact matches on the full hostname.
- It's not critical because we don't have any production DBs, yet, but I would like to make the migration populate the correct data, which requires doing lots of string manipulation directly in SQL
- I could use some help with that, if anyone does that sort of thing
- prep for #191
=> feat: make authority a queryable field on Profiles

readme.md
"Quickstart" was mispelled as "Quckstart"
=> fix: typo in readme.md

Letterbook.Core.Tests/ProfileServiceTests.cs, Letterbook.Core/Extensions/DependencyInjection.cs, Letterbook.Core/Models/Profile.cs, Letterbook.Core/ProfileService.cs, Letterbook.Core/TimelineService.cs, Letterbook.IntegrationTests/DataAdapterTests.cs, Letterbook.Workers.Tests/DependencyInjection.cs, Letterbook.Workers/Consumers/OutboundPostConsumer.cs
Fixes the audience membership when remote federated profiles follow a local profile
- Federated followers were added to the follower collection, but not the follower audience[^1]
- That caused posts not to be sent to them, because they weren't in the audience
- Obviously, that defeats the whole point
- Also adds substantial telemetry, which was useful to diagnose this problem
- Now we have it for next time
- progress on #191 
[^1]: Why is there a follower collection separate from the follower audience? Following is functionally an authorization grant to join the follower audience and view posts sent to it. But, having that authorization isn't the same as using it. A profile could join or leave the audience at their discretion, in order to tailor the content of their home feed.
=> fix: federated followers audience

.github/renovate.json5, Directory.Packages.props
don't update packages that require dotnet 9x
=> chore: renovate config

Letterbook.Core/Letterbook.Core.csproj, Letterbook.Generators/Letterbook.Generators/ITypedId.cs, Letterbook.Generators/Letterbook.Generators/Letterbook.Generators.csproj
Visual Studio can't load code generators & analyzers that target net8.0 (https://github.com/dotnet/roslyn/issues/47087, https://github.com/dotnet/roslyn-analyzers/issues/7302).
With this change, `Letterbook.Generators` will now be built twice, targeting both `netstandard2.0` and `net8.0`, and the `netstandard2.0` build will be referenced when building inside of Visual Studio.
To validate this change, I built the solution with Visual Studio and dotnet on a x64 windows machine. I ran all the tests in VS and they passed, excluding `Letterbook.IntegrationTests` and `Letterbook.Web.Tests.E2E` which failed and I assume will need additional setup.
- `Letterbook.Core`'s reference to `Letterbook.Generators` is unfortunately significantly more complex now.
- When building inside VS, it's referenced …
=> Fix building in Visual Studio by targeting multiple frameworks in Letterbook.Generators

CONTRIBUTING.md, Letterbook.Docs/_blog/2024-12-26/officeHours.md, Letterbook/Properties/launchSettings.json, docker-compose.yml, volumes/postgresql.conf
Fixes the postgres config, and other updates to docker compose and contributing guide
- use compose profiles, to run only required services
- move pg_hba.conf, to permit first-run automatic db creation
- rename launch profile, for clarity
- update quickstart to use the preferred monolith project and dev launch profile
=> chore: fix dev workflow

.github/workflows/pull-request.yml
Better performance and reliability, through caching. And also skipping unnecessary work.
- Cache libman resources properly
- now libman restores are fast and don't fail randomly
- Skip redundant implicit build and restore steps
=> ci: better caching

Letterbook.Adapter.Db/Migrations/20241209072037_FixIds.Designer.cs, Letterbook.Adapter.Db/Migrations/20250121062137_BlockAndReport.cs
added appropriate default values for new columns
=> fix: block and report migration

Letterbook.Api/Controllers/PostsController.cs, Letterbook.Api/Controllers/ProfilesController.cs, Letterbook.Core.Tests/WithMocks.cs, Letterbook.Core/Authorization/AuthorizationService.cs, Letterbook.Core/IAuthorizationService.cs
Mainly, removed the profileId arg. We're not guaranteed to have an active profile, so we should instead just use the claims.
=> internals: Updated authorization interface

Source/Letterbook.Api/Controllers/ProfilesController.cs, Source/Letterbook.Api/WebfingerProvider.cs, Source/Letterbook.Core/Extensions/UriExtensions.cs, Source/Letterbook.Core/IProfileService.cs, Source/Letterbook.Core/Models/Profile.cs, Source/Letterbook.Core/ProfileService.cs, Source/Letterbook.Web/DependencyInjection.cs, Source/Letterbook.Web/Letterbook.Web.csproj, Source/Letterbook.Web/Pages/Profile.cshtml, Source/Letterbook.Web/Pages/Profile.cshtml.cs, Source/Letterbook.Web/Pages/ProfileEdit.cshtml, Source/Letterbook.Web/Pages/ProfileEdit.cshtml.cs, Source/Letterbook.Web/Pages/Shared/_Layout.cshtml, Source/Letterbook.Web/Pages/Shared/_ProfileSelector.cshtml, Source/Letterbook.Web/Program.cs, Source/Letterbook.Web/Routes/ProfileHandleParameterTransformer.cs, Source/Letterbook.Web/Routes/ProfileIdParameterTransformer.cs, Source/Letterbook/Program.cs, Tests/Letterbook.Api.Tests/WebfingerTests.cs, Tests/Letterbook.Web.Mocks/Program.cs, Tests/Letterbook.Web.Mocks/appsettings.Development.json, Tests/Letterbook.Web.Tests/ProfileControllerTests.cs
This is a refactor to the Profile page's route parameter handling. It enables loading profiles either by handle (with or without the host) or by ID. We don't actually search by ID right now, but we're likely to as we build out more UI. This also has the side benefit of making Rider's problem detection happier. Rider used to flag the `@` in the template as an error. It's not, but it was annoying.
(Source/Letterbook.Web/Pages/Profile.cshtml)
```csharp
@page "{id}"
```
produces this route template `/profile/{id}`. This comes from the default razor pages route convention.
(Source/Letterbook.Web/DependencyInjection.cs)
```csharp
options.Conventions.AddPageRoute("/Profile", "/{id:handle}");
```
produces this route template `/{handle}` where `handle` must include the initial `@`, and optionally …
=> chore: profile url routes

Directory.Packages.props, Source/Letterbook.Adapter.ActivityPub/Mappers/AstMapper.cs, Source/Letterbook.Adapter.Db/DependencyInjection.cs, Source/Letterbook.Adapter.Db/EntityConfigs/ConfigurePost.cs, Source/Letterbook.Adapter.Db/EntityConfigs/ConfigureProfile.cs, Source/Letterbook.Adapter.Db/Migrations/20250415040209_ProfileProjectionsAndEstimates.Designer.cs, Source/Letterbook.Adapter.Db/Migrations/20250415040209_ProfileProjectionsAndEstimates.cs, Source/Letterbook.Core/Letterbook.Core.csproj, Source/Letterbook.Core/Models/Dto/FullProfileDto.cs, Source/Letterbook.Core/Models/Mappers/BaseMappings.cs, Source/Letterbook.Core/Models/Mappers/PostMappings.cs, Source/Letterbook.Core/Models/Mappers/ProfileMappings.cs, Source/Letterbook.Core/Models/Profile.cs, Tests/Letterbook.IntegrationTests/DataAdapterTests.cs, docs/OpenApi/letterbook-v1.json
Configures projections to begin to support querying complex and aggregate values. Also adds simple estimates, to track values that may be reported by peer instances.
- Adds projectable library, and some initial projectable methods
- Projections aren't all that useful on basic model objects, but they can be used to populate values on mapped or projected objects
- Automapper configs can sometimes be used as projection targets, which is helpful, and can make code reuse easier.
- But only if the mapping doesn't use several techniques that we do tend to rely on. As a rule of thumb, prefer `ConvertUsing(expr)` methods, rather than value mappers or resolvers.
- See the AutoMapper docs for details on restrictions when using projectionshttps://docs.automapper.org/en/stable/Queryable-Extensions.html …
=> feat: projected and estimated values
